# Instead of installing anything run a command that does nothing
install: true

# Instead of running tests, run a command that does nothing
script: true

# If tests pass (and in this case they always will since we're not running
# any), then purge the Cloudflare cache so the changes show up
after_success: _src/bin/purgecache

# This puts the Cloudflare API key in an environment variable so we can purge
# the cache
env:
  global:
    secure: k7KSxHsNE+WYwygZkPAywBsH0Wn3xFAm0TUyRzJk+JBlfSR4c9UvDE4mOQzTgNr8Tym6tIPB7GuDGg55cDlZCFDTY83WbN45gUlZzOArcQpzIw91eW1jAtm1EencowsO4DNkYKaRKVNsbPzhpg/DmI4wl/AC3N7LWtRPh4shz7OhMx1U09gmm/Zt9uaGGietXcMNKWs/zWEK9FGog8O9hiVmBpcUmxgLXxyT3i8iApNF1h6yqe8kyEqjC7J9c6AB91gRnNL0yhhBXJqM8G8LRYsq5i1hNp98oLNU/DYbJD/22m5zq2nJcQCvxJiZN7virVkOJXxGzHbKfkctReVHJEeIFeLmGOPKBv0xJJCkuFkaaJIG+/MeQx1ueHozFoTAh1oDJI2udTdY47QrBC17BLVdqFfWhpEVD71lr8H64qe3O5Fd4x7mXfk2Xs0/3XE8hTinopsRN5kqp2AwC4s0uepUrDRwRXSPjmTjrQ0UkqDV8V/ZqiWJxS9iG+Klj19X7CW4WgF1Wix0h//4QlANnRutpbyZjfvUWOJGwC0fpVHGHrIq8r+mOCPMFiQojexE+alZTdrPM4hj7Kbr9LPjvazX1okEH1mW30zJqUu7YDIMLkQkUckyunCrnFqUCcxqsDDmynK3GxfpYNDzTa7yZ4pyXRBMT3okmqf58Y2cS3g=
