sass:
  style: :compressed

permalink: pretty

email: info@austinmidtownchapel.org
insta: https://instagram.com/austinmidtownchapel/
facebook: https://www.facebook.com/austinmidtownchapel

nav:
-
  text: Home
  url: /
-
  text: About
  url: /about/
-
  text: Events
  url: /events/
# -
#   text: Media
#   url: /media/
-
  text: Contact
  url: /contact/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "posts"
    values:
      layout: "worship"
  -
    scope:
      path: "js"
    values:
      layout: null
