sass:
  style: :compressed

permalink: pretty

nav:
-
  text: Home
  url: /
-
  text: People
  url: /people/
-
  text: Events
  url: /events/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "posts"
    values:
      layout: "worship"
  -
    scope:
      path: "js"
    values:
      layout: null
