sass:
  style: :compressed

url: http://austinchapel.org

permalink: pretty

email: info@austinchapel.org
insta: https://instagram.com/austinchapel.tx/
facebook: https://www.facebook.com/austinmidtownchapel

people:
  aaron:
    email: aaron.r.stacy@gmail.com

nav:
-
  text: Home
  url: /
-
  text: About
  url: /about/
-
  text: Gatherings
  url: /gatherings/
-
  text: Media
  url: /media/
-
  text: Give
  url: /give/
-
  text: Contact
  url: /contact/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      type: "posts"
    values:
      layout: "worship"
  -
    scope:
      path: "js"
    values:
      layout: null

gems:
- jekyll-sitemap
